vich_uploader:
    db_driver: orm

    mappings:
       chambres_image:
           uri_prefix: /images/chambres
           upload_destination: '%kernel.project_dir%/public/images/chambres'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
